import {
  DefineWorkflow,
  Schema,
} from 'https://deno.land/x/deno_slack_sdk@2.7.0/mod.ts'
import { DeleteLocation } from '../functions/delete_location.ts'
import { GetLocation } from '../functions/get_location.ts'
import { HandleIssueMessage } from '../functions/handle_issue_message.ts'
import { UpdateContextMessage } from '../functions/update_context_message.ts'
import { VerifyCaptcha } from '../functions/verify_captcha.ts'

const HandleIssueWorkflow = DefineWorkflow({
  callback_id: 'handle_issue_wf',
  title: 'Handle issue',
  description:
    'Sends a message with the issue information and actions for it. Issues generated by the App',
  input_parameters: {
    properties: {
      uuid: {
        type: Schema.types.string,
      },
      captcha: {
        type: Schema.types.string,
      },
      reason: {
        type: Schema.types.string,
      },
      reason_id: {
        type: Schema.types.string,
      },
      dev: {
        type: Schema.types.boolean,
      },
    },
    required: [
      'uuid',
      'captcha',
      'dev',
      'reason',
    ],
  },
})

HandleIssueWorkflow.addStep(
  VerifyCaptcha,
  {
    captcha: HandleIssueWorkflow.inputs.captcha,
  },
)

const locationStep = HandleIssueWorkflow.addStep(
  GetLocation,
  {
    uuid: HandleIssueWorkflow.inputs.uuid,
    environment: HandleIssueWorkflow.inputs.dev.toString() === 'true' ? 'Test' : 'Production',
  },
)

const messageStep = HandleIssueWorkflow.addStep(
  HandleIssueMessage,
  {
    location: locationStep.outputs.location,
    environment: HandleIssueWorkflow.inputs.dev.toString() === 'true' ? 'Test' : 'Production',
    reason: HandleIssueWorkflow.inputs.reason,
    reason_id: HandleIssueWorkflow.inputs.reason_id,
  },
)

HandleIssueWorkflow.addStep(
  DeleteLocation,
  {
    uuid: locationStep.outputs.location.uuid,
    environment: HandleIssueWorkflow.inputs.dev.toString() === 'true' ? 'Test' : 'Production',
  },
)

HandleIssueWorkflow.addStep(
  UpdateContextMessage,
  {
    location: locationStep.outputs.location,
    message_ts: messageStep.outputs.message_ts,
    reviewer: messageStep.outputs.reviewer,
    environment: HandleIssueWorkflow.inputs.dev.toString() === 'true' ? 'Test' : 'Production',
    reason: HandleIssueWorkflow.inputs.reason,
    reason_id: HandleIssueWorkflow.inputs.reason_id,
    type: 'location_deleted_issue',
  },
)

export default HandleIssueWorkflow
