import { Category, Currency, type Location, LocationType, ProviderName } from '@/database'

export const locations: Record<ProviderName, Location> = {
  [ProviderName.Default]: {
    uuid: '1',
    name: 'Mercedes-Benz Arena',
    category: Category.Entertainment,
    type: LocationType.Shop,
    address: 'Kreuzbergstrasse 28, 10247, Berlin',
    accepts: [Currency.BTC, Currency.NIM, Currency.ETH],
    sells: [],
    gmaps_type: 'Stadium',
    lat: 1,
    lng: 1,
    rating: 4,
    gmaps: 'https://goo.gl/maps/ujJkv9DFuPfkwqat9',
    photo: 'https://images.unsplash.com/photo-1646491946169-76e0668b8b3f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80',
    provider: ProviderName.Default,
  },
  [ProviderName.DefaultAtm]: {
    uuid: '2',
    name: 'ATM',
    category: Category.Cash,
    type: LocationType.Atm,
    address: 'Kreuzbergstrasse 28, 10247, Berlin',
    accepts: [Currency.BTC, Currency.NIM, Currency.ETH, Currency.DASH, Currency.XLM],
    sells: [],
    gmaps_type: 'Bank',
    lat: 1,
    lng: 1,
    rating: 4,
    gmaps: 'https://goo.gl/maps/ujJkv9DFuPfkwqat9',
    provider: ProviderName.DefaultAtm,
  },
  [ProviderName.Kurant]: {
    uuid: '2',
    name: 'ATM (Kurant)',
    type: LocationType.Atm,
    category: Category.Cash,
    address: 'Kreuzbergstrasse 28, 10247, Berlin',
    accepts: [Currency.BTC, Currency.NIM],
    sells: [Currency.NIM],
    gmaps_type: 'Bank',
    lat: 1,
    lng: 1,
    rating: 4,
    gmaps: 'https://goo.gl/maps/ujJkv9DFuPfkwqat9',
    provider: ProviderName.Kurant,
  },
  [ProviderName.Bluecode]: {
    uuid: '3',
    name: 'Room 88',
    type: LocationType.Shop,
    category: Category.FoodDrinks,
    address: 'Kreuzbergstrasse 28, 10247, Berlin',
    accepts: [Currency.BTC, Currency.NIM, Currency.ETH],
    sells: [],
    gmaps_type: 'Stadium',
    lat: 1,
    lng: 1,
    rating: 4,
    gmaps: 'https://goo.gl/maps/ujJkv9DFuPfkwqat9',
    photo: 'https://images.unsplash.com/photo-1543007631-283050bb3e8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
    provider: ProviderName.Bluecode,
  },
  [ProviderName.GoCrypto]: {
    uuid: '4',
    name: 'Mercedes-Benz Arena',
    type: LocationType.Shop,
    category: Category.Entertainment,
    address: 'Kreuzbergstrasse 28, 10247, Berlin',
    accepts: [Currency.BTC, Currency.NIM, Currency.ETH],
    sells: [],
    gmaps_type: 'Stadium',
    lat: 1,
    lng: 1,
    rating: 4,
    gmaps: 'https://goo.gl/maps/ujJkv9DFuPfkwqat9',
    photo: 'https://images.unsplash.com/photo-1646491946169-76e0668b8b3f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80',
    provider: ProviderName.GoCrypto,
  },
  [ProviderName.CryptopaymentLink]: {
    uuid: '5',
    name: 'Mercedes-Benz Arena',
    type: LocationType.Shop,
    category: Category.Entertainment,
    address: 'Kreuzbergstrasse 28, 10247, Berlin',
    accepts: [Currency.BTC, Currency.NIM, Currency.USDC_POLYGON],
    sells: [],
    gmaps_type: 'Stadium',
    lat: 1,
    lng: 1,
    rating: 4,
    gmaps: 'https://goo.gl/maps/ujJkv9DFuPfkwqat9',
    photo: 'https://images.unsplash.com/photo-1646491946169-76e0668b8b3f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80',
    provider: ProviderName.CryptopaymentLink,
  },
  [ProviderName.Edenia]: {
    uuid: '5',
    name: 'Mercedes-Benz Arena',
    type: LocationType.Shop,
    category: Category.Cash,
    address: 'Kreuzbergstrasse 28, 10247, Berlin',
    accepts: [Currency.BTC, Currency.NIM, Currency.USDC_POLYGON],
    sells: [],
    gmaps_type: 'Stadium',
    lat: 1,
    lng: 1,
    rating: 4,
    gmaps: 'https://goo.gl/maps/ujJkv9DFuPfkwqat9',
    provider: ProviderName.Edenia,
  },
}
