/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicInfoLocation: typeof import('./components/BasicInfoLocation.vue')['default']
    ClusterMarkers: typeof import('./components/ClusterMarkers.vue')['default']
    CompactView: typeof import('./components/CompactView.vue')['default']
    CryptocityCard: typeof import('./components/CryptocityCard.vue')['default']
    'CryptocityCard.story': typeof import('./components/CryptocityCard.story.vue')['default']
    CryptoList: typeof import('./components/CryptoList.vue')['default']
    CryptoMapModal: typeof import('./components/CryptoMapModal.vue')['default']
    'CryptoMapModal.story': typeof import('./components/CryptoMapModal.story.vue')['default']
    CurrencySelector: typeof import('./components/CurrencySelector.vue')['default']
    DesktopList: typeof import('./components/DesktopList.vue')['default']
    'DesktopList.story': typeof import('./components/DesktopList.story.vue')['default']
    DesktopSearch: typeof import('./components/DesktopSearch.vue')['default']
    DesktopView: typeof import('./components/DesktopView.vue')['default']
    FAQ: typeof import('./components/FAQ.vue')['default']
    InteractionBar: typeof import('./components/InteractionBar.vue')['default']
    LocationCandidate: typeof import('./components/LocationCandidate.vue')['default']
    LocationCard: typeof import('./components/LocationCard.vue')['default']
    'LocationCard.story': typeof import('./components/LocationCard.story.vue')['default']
    LocationCardBg: typeof import('./components/LocationCardBg.vue')['default']
    LocationCardDotsMenu: typeof import('./components/LocationCardDotsMenu.vue')['default']
    LocationExternalUrl: typeof import('./components/LocationExternalUrl.vue')['default']
    LocationSearchBox: typeof import('./components/LocationSearchBox.vue')['default']
    MapControls: typeof import('./components/MapControls.vue')['default']
    MapMarkers: typeof import('./components/MapMarkers.vue')['default']
    MapView: typeof import('./components/MapView.vue')['default']
    MobileList: typeof import('./components/MobileList.vue')['default']
    'MobileList.story': typeof import('./components/MobileList.story.vue')['default']
    MobileSearch: typeof import('./components/MobileSearch.vue')['default']
    MobileView: typeof import('./components/MobileView.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    MultiSelector: typeof import('./components/MultiSelector.vue')['default']
    ReportLocation: typeof import('./components/ReportLocation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSuggestions: typeof import('./components/SearchSuggestions.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    SheetModal: typeof import('./components/SheetModal.vue')['default']
    'SheetModal.story': typeof import('./components/SheetModal.story.vue')['default']
    SingleMarker: typeof import('./components/SingleMarker.vue')['default']
    SingleMarkersDesktop: typeof import('./components/SingleMarkersDesktop.vue')['default']
    TheMapInstance: typeof import('./components/TheMapInstance.vue')['default']
    TriangleSelector: typeof import('./components/TriangleSelector.vue')['default']
    'TriangleSelector.story': typeof import('./components/TriangleSelector.story.vue')['default']
    UserLocationMarker: typeof import('./components/UserLocationMarker.vue')['default']
  }
}
