/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Establishments map API is serves a list of establishments that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CryptoEstablishmentProvidersInner
 */
export interface CryptoEstablishmentProvidersInner {
    /**
     * 
     * @type {number}
     * @memberof CryptoEstablishmentProvidersInner
     */
    id: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CryptoEstablishmentProvidersInner
     */
    buy: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CryptoEstablishmentProvidersInner
     */
    sell: Array<string>;
}

/**
 * Check if a given object implements the CryptoEstablishmentProvidersInner interface.
 */
export function instanceOfCryptoEstablishmentProvidersInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "buy" in value;
    isInstance = isInstance && "sell" in value;

    return isInstance;
}

export function CryptoEstablishmentProvidersInnerFromJSON(json: any): CryptoEstablishmentProvidersInner {
    return CryptoEstablishmentProvidersInnerFromJSONTyped(json, false);
}

export function CryptoEstablishmentProvidersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoEstablishmentProvidersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'buy': json['buy'],
        'sell': json['sell'],
    };
}

export function CryptoEstablishmentProvidersInnerToJSON(value?: CryptoEstablishmentProvidersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'buy': value.buy,
        'sell': value.sell,
    };
}

