/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Establishments map API is serves a list of establishments that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProviders200ResponseCta
 */
export interface GetProviders200ResponseCta {
    /**
     * 
     * @type {string}
     * @memberof GetProviders200ResponseCta
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProviders200ResponseCta
     */
    text?: string;
}

/**
 * Check if a given object implements the GetProviders200ResponseCta interface.
 */
export function instanceOfGetProviders200ResponseCta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetProviders200ResponseCtaFromJSON(json: any): GetProviders200ResponseCta {
    return GetProviders200ResponseCtaFromJSONTyped(json, false);
}

export function GetProviders200ResponseCtaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProviders200ResponseCta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
        'text': !exists(json, 'text') ? undefined : json['text'],
    };
}

export function GetProviders200ResponseCtaToJSON(value?: GetProviders200ResponseCta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
        'text': value.text,
    };
}

