/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Establishments map API is serves a list of establishments that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetProviders200ResponseCta } from './GetProviders200ResponseCta';
import {
    GetProviders200ResponseCtaFromJSON,
    GetProviders200ResponseCtaFromJSONTyped,
    GetProviders200ResponseCtaToJSON,
} from './GetProviders200ResponseCta';
import type { GetProviders200ResponseStyle } from './GetProviders200ResponseStyle';
import {
    GetProviders200ResponseStyleFromJSON,
    GetProviders200ResponseStyleFromJSONTyped,
    GetProviders200ResponseStyleToJSON,
} from './GetProviders200ResponseStyle';

/**
 * 
 * @export
 * @interface GetProviders200Response
 */
export interface GetProviders200Response {
    /**
     * 
     * @type {number}
     * @memberof GetProviders200Response
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetProviders200Response
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetProviders200Response
     */
    messageEn: string;
    /**
     * 
     * @type {string}
     * @memberof GetProviders200Response
     */
    messageEs: string;
    /**
     * 
     * @type {string}
     * @memberof GetProviders200Response
     */
    messageDe: string;
    /**
     * 
     * @type {string}
     * @memberof GetProviders200Response
     */
    logo: string;
    /**
     * 
     * @type {GetProviders200ResponseStyle}
     * @memberof GetProviders200Response
     */
    style: GetProviders200ResponseStyle;
    /**
     * 
     * @type {GetProviders200ResponseCta}
     * @memberof GetProviders200Response
     */
    cta: GetProviders200ResponseCta;
    /**
     * Create
     * @type {any}
     * @memberof GetProviders200Response
     */
    _201?: any | null;
    /**
     * Not Found
     * @type {any}
     * @memberof GetProviders200Response
     */
    _404?: any | null;
}

/**
 * Check if a given object implements the GetProviders200Response interface.
 */
export function instanceOfGetProviders200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "messageEn" in value;
    isInstance = isInstance && "messageEs" in value;
    isInstance = isInstance && "messageDe" in value;
    isInstance = isInstance && "logo" in value;
    isInstance = isInstance && "style" in value;
    isInstance = isInstance && "cta" in value;

    return isInstance;
}

export function GetProviders200ResponseFromJSON(json: any): GetProviders200Response {
    return GetProviders200ResponseFromJSONTyped(json, false);
}

export function GetProviders200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProviders200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'messageEn': json['message_en'],
        'messageEs': json['message_es'],
        'messageDe': json['message_de'],
        'logo': json['logo'],
        'style': GetProviders200ResponseStyleFromJSON(json['style']),
        'cta': GetProviders200ResponseCtaFromJSON(json['cta']),
        '_201': !exists(json, '201') ? undefined : json['201'],
        '_404': !exists(json, '404') ? undefined : json['404'],
    };
}

export function GetProviders200ResponseToJSON(value?: GetProviders200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'message_en': value.messageEn,
        'message_es': value.messageEs,
        'message_de': value.messageDe,
        'logo': value.logo,
        'style': GetProviders200ResponseStyleToJSON(value.style),
        'cta': GetProviders200ResponseCtaToJSON(value.cta),
        '201': value._201,
        '404': value._404,
    };
}

