/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Establishments map API is serves a list of establishments that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProviders200ResponseStyle
 */
export interface GetProviders200ResponseStyle {
    /**
     * 
     * @type {number}
     * @memberof GetProviders200ResponseStyle
     */
    opacity?: number;
    /**
     * 
     * @type {string}
     * @memberof GetProviders200ResponseStyle
     */
    background?: string;
}

/**
 * Check if a given object implements the GetProviders200ResponseStyle interface.
 */
export function instanceOfGetProviders200ResponseStyle(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetProviders200ResponseStyleFromJSON(json: any): GetProviders200ResponseStyle {
    return GetProviders200ResponseStyleFromJSONTyped(json, false);
}

export function GetProviders200ResponseStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProviders200ResponseStyle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'opacity': !exists(json, 'opacity') ? undefined : json['opacity'],
        'background': !exists(json, 'background') ? undefined : json['background'],
    };
}

export function GetProviders200ResponseStyleToJSON(value?: GetProviders200ResponseStyle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'opacity': value.opacity,
        'background': value.background,
    };
}

