/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Establishments map API is serves a list of establishments that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderCrypto
 */
export interface ProviderCrypto {
    /**
     * 
     * @type {number}
     * @memberof ProviderCrypto
     */
    id: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProviderCrypto
     */
    buy: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProviderCrypto
     */
    sell: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProviderCrypto
     */
    both: Array<string>;
}

/**
 * Check if a given object implements the ProviderCrypto interface.
 */
export function instanceOfProviderCrypto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "buy" in value;
    isInstance = isInstance && "sell" in value;
    isInstance = isInstance && "both" in value;

    return isInstance;
}

export function ProviderCryptoFromJSON(json: any): ProviderCrypto {
    return ProviderCryptoFromJSONTyped(json, false);
}

export function ProviderCryptoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderCrypto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'buy': json['buy'],
        'sell': json['sell'],
        'both': json['both'],
    };
}

export function ProviderCryptoToJSON(value?: ProviderCrypto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'buy': value.buy,
        'sell': value.sell,
        'both': value.both,
    };
}

